CREATE OR ALTER TABLE CUSTOMER (
    CUSTOMER_ID        INT NOT NULL,
    LAST_NAME          VARCHAR(100),
    FIRST_NAME         VARCHAR(100),
    EMAIL_ADDRESS      VARCHAR(100),
    COMPANY_NAME       VARCHAR(100),
    PHONE_NUMBER       VARCHAR(100),
    ADDRESS_LINE_1     VARCHAR(150),
    ADDRESS_LINE_2     VARCHAR(150),
    CITY_NAME          VARCHAR(100),
    STATE_NAME         VARCHAR(100),
    POSTAL_CODE        VARCHAR(15),
    COUNTRY_NAME       VARCHAR(50)
);
